# Learning Outcomes
1. Overview of CV
2. Revisit some important concepts of image as Numpy array.
3. Cropping. Why? One of the data aumentation techniques in deep learning model development
4. Splitting and merging of color channels 
5. Mathematical operations
6. Image blending (add 2 image together)

## Setup (Import Modules)

In [1]:
!pip install opencv-contrib-python

In [2]:
import cv2 as cv

def show_img(window_name, img, adjust=False):
    """3 arguments: window name, source images, boolean to adjust to screen size"""
    if adjust:
        cv.namedWindow(window_name, cv.WINDOW_NORMAL)
    else:
        cv.namedWindow(window_name)

    cv.imshow(window_name, img)
    cv.waitKey(0)
    cv.destroyAllWindows()
    

In [3]:
import sys
assert sys.version_info >= (3, 7)

import numpy as np
import cv2 as cv
from util_func import show_img

np.random.seed(99)

if not cv.useOptimized():
    
    cv.setUseOptimized(True)
    
cv.useOptimized()


True

## Image as Numpy Array

In [4]:
img = np.zeros((2, 4), dtype = np.uint8)
print(img)

[[0 0 0 0]
 [0 0 0 0]]


The above `img` variable belongs to grayscale image. Another primary types of image is `color image`.

In [5]:
img_color = cv.cvtColor(img, cv.COLOR_GRAY2BGR)
print(img_color)

[[[0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]]]


In [6]:
img[0, 1] = 50
img[1, 2] = 100
print(img)

[[  0  50   0   0]
 [  0   0 100   0]]


In [7]:
img_color1 = cv.cvtColor(img, cv.COLOR_GRAY2BGR)
print(img_color1)

[[[  0   0   0]
  [ 50  50  50]
  [  0   0   0]
  [  0   0   0]]

 [[  0   0   0]
  [  0   0   0]
  [100 100 100]
  [  0   0   0]]]


## Access elements in an array

In [8]:
img = cv.imread("images/lena.jfif")

a = img[49, 199, 2]
b = img.item(49, 199, 2)
a == b

True

In [9]:
%timeit a = img[49, 199, 2]
%timeit b = img.item(49, 199, 2)

300 ns ± 38 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
298 ns ± 14.4 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


## Numpy array slicing


In [10]:
# Extract the top left region of lena image
show_img("lena", img)

In [11]:
h, w = img.shape[:2]

topleft = img[:h // 2, :w // 2]
show_img("topleft", topleft)


In [12]:
# Extract central region of the image
yc, xc = h // 2, w // 2

centre = img[yc - 30:yc + 30, xc - 30:xc + 30]

show_img("centre", centre)

### Exercise

In [13]:
# Create white image
#white = np.zeros((200, 200)) + 255
#white = np.uint8(white)

white = np.ones((200, 200))

show_img("white", white)

In [ ]:
# Extract flower
img = cv.imread("images/flower.jfif")

show_img("flower", img)

In [14]:
[i for i in dir(cv) if i.startswith('')]

['ACCESS_FAST',
 'ACCESS_MASK',
 'ACCESS_READ',
 'ACCESS_RW',
 'ACCESS_WRITE',
 'ADAPTIVE_THRESH_GAUSSIAN_C',
 'ADAPTIVE_THRESH_MEAN_C',
 'AGAST_FEATURE_DETECTOR_AGAST_5_8',
 'AGAST_FEATURE_DETECTOR_AGAST_7_12D',
 'AGAST_FEATURE_DETECTOR_AGAST_7_12S',
 'AGAST_FEATURE_DETECTOR_NONMAX_SUPPRESSION',
 'AGAST_FEATURE_DETECTOR_OAST_9_16',
 'AGAST_FEATURE_DETECTOR_THRESHOLD',
 'AKAZE',
 'AKAZE_DESCRIPTOR_KAZE',
 'AKAZE_DESCRIPTOR_KAZE_UPRIGHT',
 'AKAZE_DESCRIPTOR_MLDB',
 'AKAZE_DESCRIPTOR_MLDB_UPRIGHT',
 'AKAZE_create',
 'AffineFeature',
 'AffineFeature_create',
 'AffineTransformer',
 'AgastFeatureDetector',
 'AgastFeatureDetector_AGAST_5_8',
 'AgastFeatureDetector_AGAST_7_12d',
 'AgastFeatureDetector_AGAST_7_12s',
 'AgastFeatureDetector_NONMAX_SUPPRESSION',
 'AgastFeatureDetector_OAST_9_16',
 'AgastFeatureDetector_THRESHOLD',
 'AgastFeatureDetector_create',
 'Algorithm',
 'AlignExposures',
 'AlignMTB',
 'AsyncArray',
 'BFMatcher',
 'BFMatcher_create',
 'BORDER_CONSTANT',
 'BORDER_DEFAULT',
 

In [16]:
# 1 way: callback function
img = cv.imread("")

def rect_region(event, x, y, flags, params):
    """This is mouseclick callback function"""
    if event == cv.EVENT_LBUTTONDOWN:
        print((x, y))
        cv.circle(img, (x. y), 1, (0, 0, 255), -1)
        cv.imshow("img", img)
        
cv.imshow("img", img)
cv.setMouseCallback("img", react_region)
cv.waitKey(0)
cv.destroyAllWindows()

error: OpenCV(4.8.0) D:\a\opencv-python\opencv-python\opencv\modules\highgui\src\window.cpp:971: error: (-215:Assertion failed) size.width>0 && size.height>0 in function 'cv::imshow'


In [17]:
flower = img_copy[39:122, 93:175]

show_img("flower", flower)

NameError: name 'img_copy' is not defined

In [18]:
# 2 way: 
img = cv.imread("images/flower.jfif")
bbox = cv.selectROI("img", img)

# (x, y, w, h)
flower = img[int(bbox[1]): int(bbox[1] + bbox[3]),
            int(bbox[0]): int(bbox[0] + bbox[2])]

show_img("flower", flower)

error: OpenCV(4.8.0) D:\a\opencv-python\opencv-python\opencv\modules\highgui\src\window.cpp:971: error: (-215:Assertion failed) size.width>0 && size.height>0 in function 'cv::imshow'


In [19]:
# 3 way: paint app

In [20]:
# generate a repeating pattern
img_arr = np.zeros((30, 30), dtype = np.uint8)

img_arr[:10, 10:20] = 255
img_arr[10:20, :10] = 255
img_arr[10:20, :20] = 255
img_arr[20:, 10:20] = 255

img = np.tile(img_arr, (3, 3))

show_img("pattern", img)

## Image Cropping
Why?
- Remove unwanted objects.
- Rule of thirds. Seperate images into $3 \times 3$ grids, and we place our camera in a way such that the object of internet is on the grid line or its intersection, the picture would look more appealing.
- Oe of the data augmentation techniques.

In [21]:
img = cv.imread("images/dog.jfif")
img_copy = img.copy()

#parameter definition
h, w = img.shape[:2]
n_vertical_grids = 4
n_horizontal_grids = 4

# we need to get the number of pixel for column and row
M = int(h / n_vertical_grids)
N = int(w / n_horizontal_grids)

tiles = []
for y in range(0, h, M):
    for x in range(0, w, N):
        x1 = x + N
        y1 = y + M
        
        if x1 > w and y1 > h:
            x1 = w - 1
            y1 = h -1
            cv.rectangle(img_copy, (x, y), (x1, y1), (0, 255, 0), 1)
            tile = img[y:h, x:w]
            tiles.append(tile)
            
        elif y1 > h:
            y1 = h -1
            cv.rectangle(img_copy, (x, y), (x1, y1), (0, 255, 0), 1)
            tile = img[y:h, x:x1]
            tiles.append(tile)
            
        elif x1 > w:
            x1 = w -1
            cv.rectangle(img_copy, (x, y), (x1, y1), (0, 255, 0), 1) 
            tile = img[y:y1, x:w]
            tiles.append(tile)
            
        else:
            cv.rectangle(img_copy, (x, y), (x1, y1), (0, 255, 0), 1) 
            tile = img[y:y1, x:x1]
            tiles.append(tile)

show_img("crop", img_copy)

In [23]:
show_img("patch", tiles[5])

## Splitting and merging of color channels

In [ ]:
img = cv.imread("images/lena.jfif")
# split image into seperate channels
b, g, r = cv.split(img)
# merge
img_merge = cv.merge((b, g, r))

# test if the two arrays are the same
np.array_equals(img, img_merge)

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
fig, (ax1, ax2, ax3) = plt.subplots(1, 3, figsize = (12, 4), sharey = True)
fig.subtitle("different color channels")

ax1.imshow(b, cmap = plt.cm.gray)
ax1.set(title = "blue channel", xticks = [], yticks[])
ax2.imshow(b, cmap = plt.cm.gray)
ax2.set(title = "green channel", xticks = [], yticks[])
ax3.imshow(b, cmap = plt.cm.gray)
ax3.set(title = "red channel", xticks = [], yticks[])

###
plt._layout()
plt.show()

### Exercise

In [ ]:
### Apply color filter
img = cv.imread("images/dog.jfif")

colors = ("blue", "green", "red")

channels = cv.split(img)

imgs = []
for i, ch in enumerate(channels):
    img_arr = np.zeros_like(img)
    img_arr[:, :, i] = ch
    imgs.append(img_arr)
    
for img, c in zip(imgs, colors):
    cv.imshow(c, img)
    
cv.waitKey(0)
cv.destroyAllWindows()

## Point operators (mathematical operations)
$$f_{trans}(\textbf{x}) = \alpha f(\textbf{x}) + \beta$$

In [ ]:
np.uint8(np.array([-2, 0, 255, 300]))

In [ ]:
def point_op(img, alpha, beta):
    """point operators. Arguments:
    1. Source image
    2. multiplier
    3. comtrast"""
    img = img.astype(float)
    res = alpha * img + beta
    res = np.clip(res, 0, 25)
    return np.uint8(res)

In [ ]:
# enhance brightness and contrast
img = cv.imread("images/bridge.jfif")

transform = point_op(img, 2, 30)

cv.imshow("original", img)
show_img("transform", transform)

In [ ]:
transform2 = point_op(img, 1, -80)

cv.imshow("original", img)
show_img("transform", transform2)

## Gamma Correction
$$ O = (\frac{I}{255})^\gamma \times 255 $$

In [ ]:
gamma = 1 / 2.2

LookUpTable = np.empty((1, 256), dtype = np.uint8)
for i in range (256):
    LookUpTable[0, i] = np.clip(pow(i / 255, gamma) * 255, 0, 255)
    
img = cv.imread("image/mountains_propo.jpg")
res = cv.LUT(img, LookUpTable)

cv.nameofWindow("original", cv.WINDOW_NORMAL)
cv.imshow("original", img)
show_img("gamma correction", res, adjust = True)

## Image Blending (add 2 image together)
get a sense of transparency

$$(\textbf{x}) = \alpha f((\textbf{x}) + (1 - \alpha) h (\textbf{x}) + \beta$$

In [ ]:
img = cv.imread('images/lena.jfif')

img2 = cv.imread("images/coins.jfif")

# resize img2
alpha = 0.8
h, w = img.shape[:2]
img2 = cv.resize(img2, (w, h))

# blending
res = cv.addWeighted(img, aplha, img2, 1 - alpha, 0)

cv.imshow("img1", img)
cv.imshow("img2", img2)
show_img("blending", res)

## Exercise


In [28]:
# Question 1
import matplotlib.pyplot as plt

weight, height = 400, 400
img = np.random.randint(0, 256, size = (height, weight, 3), dtype = np.uint8)
img_gray = cv.cvtColor(img, cv.COLOR_BGR2GRAY)

cv.imshow("Image", img)
cv.imshow("Grayscale Image", img_gray)

cv.waitKey(0)
cv.destroyAllWindows()


In [ ]:
# Question 2


In [29]:
# Question 3
img = cv.imread("images/lena.jfif")
img2 = cv.imread("images/coins.jfif")

# resize img2
h, w = img.shape[:2]
img2 = cv.resize(img2, (w, h))

for alpha in np.arange(0, 1.1, 0.1):
    # blending
    res = cv.addWeighted(img, alpha, img2, 1-alpha, 0)

    #cv.imshow('lena', img)
    #cv.imshow('reshaped coin', img2)
    cv.imshow('Image Blending', res)
    cv.waitKey(0)
    cv.destroyAllWindows()
    

In [ ]:
# Question 4
